apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: springcm
data:
  db_url: jdbc:postgresql://mydb.ciedlgccygzi.ap-south-1.rds.amazonaws.com:5432/mydb?createDatabaseIfNotExist=true
  db_username: postgres
